/*
 * Copyright (c) 2021 Snowflake Computing Inc. All rights reserved.
 */

package net.snowflake.ingest.streaming.internal;

/**
 * The request that sends to Snowflake to register one or more blobs generated by the flush service
 */
public class RegisterBlobRequest {}
