/*
 * Copyright (c) 2021 Snowflake Computing Inc. All rights reserved.
 */

package net.snowflake.ingest.streaming.internal;

/** Represents the internal stage that will hold the blobs generated by the client */
public class SnowflakeInternalStage {}
