  build-windows:
    name: Build & Test - Windows, JDK ${{ matrix.java }}, Cloud ${{ matrix.snowflake_cloud }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        snowflake_cloud: [ 'AWS', 'AZURE', 'GCP' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
          cache-dependency-path: '**/pom.xml'
      - name: Decrypt profile.json for Cloud ${{ matrix.snowflake_cloud }} on Windows Powershell
        env:
          DECRYPTION_PASSPHRASE: ${{ secrets.PROFILE_JSON_DECRYPT_PASSPHRASE }}
        shell: pwsh
        run: |
          ./scripts/decrypt_secret_windows.ps1 -SnowflakeDeployment '${{ matrix.snowflake_cloud }}'
      - name: Unit & Integration Test (Windows)
        continue-on-error: false
        env:
          MAVEN_OPTS: >-
            -Dmaven.wagon.http.pool=false
            -Dmaven.wagon.http.retryHandler.count=3
            -Dmaven.wagon.http.retryHandler.requestSentEnabled=true
            -Dmaven.wagon.rto=60000
            -Dmaven.wagon.connectTimeout=30000
            -Dhttp.tcp.nodelay=true
            -Dhttp.keepAlive=false
        run: |
          mvn -DghActionsIT -Dnot-shadeDep -D"failsafe.excludedGroups"="net.snowflake.ingest.IcebergIT" verify --batch-mode --no-transfer-progress -Dhttp.socketTimeout=60000 