name: Snyk PR
on:
  pull_request:
    branches:
      - master
jobs:
  snyk:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'sfc-gh-snyk-sca-sa' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Checkout Action
      uses: actions/checkout@v3
      with:
        repository: snowflakedb/whitesource-actions
        token: ${{ secrets.WHITESOURCE_ACTION_TOKEN }}
        path: whitesource-actions

    - name: nyk Pull Request Scan Check
      uses: ./whitesource-actions/snyk-pr
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      with:
        jira_token: ${{ secrets.JIRA_TOKEN_PUBLIC_REPO }}
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        amend: false 